server:
  port: 8050
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres                             
    password: manh1105                                
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate                           
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yml
